//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM.Web {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCM.Web.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontot låst.
        /// </summary>
        public static string Account_Locked {
            get {
                return ResourceManager.GetString("Account_Locked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontotyp.
        /// </summary>
        public static string Account_Type {
            get {
                return ResourceManager.GetString("Account_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP-konton.
        /// </summary>
        public static string Accounts {
            get {
                return ResourceManager.GetString("Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbelklicka för att lägga till kommentar.
        /// </summary>
        public static string Add_Comment {
            get {
                return ResourceManager.GetString("Add_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string Administration {
            get {
                return ResourceManager.GetString("Administration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alla.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Api.
        /// </summary>
        public static string Api {
            get {
                return ResourceManager.GetString("Api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljudläge.
        /// </summary>
        public static string Audio_Mode {
            get {
                return ResourceManager.GetString("Audio_Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ljudingångar.
        /// </summary>
        public static string AudioInputs {
            get {
                return ResourceManager.GetString("AudioInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medel.
        /// </summary>
        public static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Börjar med.
        /// </summary>
        public static string BeginsWith {
            get {
                return ResourceManager.GetString("BeginsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtal.
        /// </summary>
        public static string Call {
            get {
                return ResourceManager.GetString("Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtalstid.
        /// </summary>
        public static string Call_Duration {
            get {
                return ResourceManager.GetString("Call_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtidiga samtal per timme.
        /// </summary>
        public static string Call_Sim24Hour {
            get {
                return ResourceManager.GetString("Call_Sim24Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtidiga samtal.
        /// </summary>
        public static string Call_Simultaneous {
            get {
                return ResourceManager.GetString("Call_Simultaneous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtalstid.
        /// </summary>
        public static string Call_Time {
            get {
                return ResourceManager.GetString("Call_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtal till.
        /// </summary>
        public static string Callee {
            get {
                return ResourceManager.GetString("Callee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtal från.
        /// </summary>
        public static string Caller {
            get {
                return ResourceManager.GetString("Caller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtal.
        /// </summary>
        public static string Calls {
            get {
                return ResourceManager.GetString("Calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avbryt.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operatör förbindelse id.
        /// </summary>
        public static string Carrier_Connection_Id {
            get {
                return ResourceManager.GetString("Carrier_Connection_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CCM.
        /// </summary>
        public static string CcmUser {
            get {
                return ResourceManager.GetString("CcmUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIDR IPv4.
        /// </summary>
        public static string Cidr {
            get {
                return ResourceManager.GetString("Cidr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIDR IPv6.
        /// </summary>
        public static string CidrV6 {
            get {
                return ResourceManager.GetString("CidrV6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Städer.
        /// </summary>
        public static string Cities {
            get {
                return ResourceManager.GetString("Cities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stad.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stäng.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodarstyrning.
        /// </summary>
        public static string Codec_Control {
            get {
                return ResourceManager.GetString("Codec_Control", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställningar kodarkontroll.
        /// </summary>
        public static string Codec_Control_Settings {
            get {
                return ResourceManager.GetString("Codec_Control_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag är säker på att jag vill.
        /// </summary>
        public static string Codec_I_Am_Sure {
            get {
                return ResourceManager.GetString("Codec_I_Am_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodar-presets.
        /// </summary>
        public static string Codec_Presets {
            get {
                return ResourceManager.GetString("Codec_Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag är säker på att jag vill starta om kodaren.
        /// </summary>
        public static string Codec_Reboot_First_Confirm {
            get {
                return ResourceManager.GetString("Codec_Reboot_First_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag har kontrollerat att kodaren inte används.
        /// </summary>
        public static string Codec_Reboot_Second_Confirm {
            get {
                return ResourceManager.GetString("Codec_Reboot_Second_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodartyp.
        /// </summary>
        public static string Codec_Type {
            get {
                return ResourceManager.GetString("Codec_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodartyper.
        /// </summary>
        public static string Codec_Types {
            get {
                return ResourceManager.GetString("Codec_Types", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPO.
        /// </summary>
        public static string CodecGPO {
            get {
                return ResourceManager.GetString("CodecGPO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Färg.
        /// </summary>
        public static string Color {
            get {
                return ResourceManager.GetString("Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommentar.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekräfta lösenord.
        /// </summary>
        public static string Confirm_Password {
            get {
                return ResourceManager.GetString("Confirm_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansluten.
        /// </summary>
        public static string Connected {
            get {
                return ResourceManager.GetString("Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ansluten till.
        /// </summary>
        public static string ConnectedTo {
            get {
                return ResourceManager.GetString("ConnectedTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innehåller.
        /// </summary>
        public static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dB nivå.
        /// </summary>
        public static string Db_Level {
            get {
                return ResourceManager.GetString("Db_Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dB nivå värden.
        /// </summary>
        public static string Db_Level_Values {
            get {
                return ResourceManager.GetString("Db_Level_Values", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort konto.
        /// </summary>
        public static string Delete_Account {
            get {
                return ResourceManager.GetString("Delete_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort detta konto?.
        /// </summary>
        public static string Delete_Account_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Account_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort samtal.
        /// </summary>
        public static string Delete_Call {
            get {
                return ResourceManager.GetString("Delete_Call", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort samtalet mellan [from] och [to] som startade [start] från CCM? Observera att samtalet bara tas bort från CCM..
        /// </summary>
        public static string Delete_Call_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Call_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja jag är säker.
        /// </summary>
        public static string Delete_Call_I_Am_Sure {
            get {
                return ResourceManager.GetString("Delete_Call_I_Am_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag har kontrollerat att samtalet verkligen inte pågår.
        /// </summary>
        public static string Delete_Call_I_Have_Checked {
            get {
                return ResourceManager.GetString("Delete_Call_I_Have_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort stad.
        /// </summary>
        public static string Delete_City {
            get {
                return ResourceManager.GetString("Delete_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna stad?.
        /// </summary>
        public static string Delete_City_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_City_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort kodartyp.
        /// </summary>
        public static string Delete_Codec_Type {
            get {
                return ResourceManager.GetString("Delete_Codec_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna kodartyp?.
        /// </summary>
        public static string Delete_Codec_Type_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Codec_Type_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort filter.
        /// </summary>
        public static string Delete_Filter {
            get {
                return ResourceManager.GetString("Delete_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort detta filter?.
        /// </summary>
        public static string Delete_Filter_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Filter_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort grupp.
        /// </summary>
        public static string Delete_Group {
            get {
                return ResourceManager.GetString("Delete_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna grupp?.
        /// </summary>
        public static string Delete_Group_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Group_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort plats.
        /// </summary>
        public static string Delete_Location {
            get {
                return ResourceManager.GetString("Delete_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna plats?.
        /// </summary>
        public static string Delete_Location_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Location_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort metatyp.
        /// </summary>
        public static string Delete_MetaType {
            get {
                return ResourceManager.GetString("Delete_MetaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna metatyp?.
        /// </summary>
        public static string Delete_MetaType_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_MetaType_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort ägare.
        /// </summary>
        public static string Delete_Owner {
            get {
                return ResourceManager.GetString("Delete_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna ägare?.
        /// </summary>
        public static string Delete_Owner_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Owner_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort preset.
        /// </summary>
        public static string Delete_Preset {
            get {
                return ResourceManager.GetString("Delete_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna preset?.
        /// </summary>
        public static string Delete_Preset_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Preset_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort profil.
        /// </summary>
        public static string Delete_Profile {
            get {
                return ResourceManager.GetString("Delete_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna profil?.
        /// </summary>
        public static string Delete_Profile_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Profile_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort grupp.
        /// </summary>
        public static string Delete_ProfileGroup {
            get {
                return ResourceManager.GetString("Delete_ProfileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna grupp?.
        /// </summary>
        public static string Delete_ProfileGroup_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_ProfileGroup_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort region.
        /// </summary>
        public static string Delete_Region {
            get {
                return ResourceManager.GetString("Delete_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna region?.
        /// </summary>
        public static string Delete_Region_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_Region_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort användare.
        /// </summary>
        public static string Delete_User {
            get {
                return ResourceManager.GetString("Delete_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna användare?.
        /// </summary>
        public static string Delete_User_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_User_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort kodarmodell.
        /// </summary>
        public static string Delete_UserAgent {
            get {
                return ResourceManager.GetString("Delete_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna kodarmodell?.
        /// </summary>
        public static string Delete_UserAgent_Are_You_Sure {
            get {
                return ResourceManager.GetString("Delete_UserAgent_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beskrivning.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej uppkopplad.
        /// </summary>
        public static string Disconnected {
            get {
                return ResourceManager.GetString("Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visningsnamn.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klart.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladda ner csv-fil.
        /// </summary>
        public static string Download_Csv {
            get {
                return ResourceManager.GetString("Download_Csv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra konto.
        /// </summary>
        public static string Edit_Account {
            get {
                return ResourceManager.GetString("Edit_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra stad.
        /// </summary>
        public static string Edit_City {
            get {
                return ResourceManager.GetString("Edit_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra kodartyp.
        /// </summary>
        public static string Edit_Codec_Type {
            get {
                return ResourceManager.GetString("Edit_Codec_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dubbelklicka för att redigera kommentar.
        /// </summary>
        public static string Edit_Comment {
            get {
                return ResourceManager.GetString("Edit_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra grupp.
        /// </summary>
        public static string Edit_Group {
            get {
                return ResourceManager.GetString("Edit_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra plats.
        /// </summary>
        public static string Edit_Location {
            get {
                return ResourceManager.GetString("Edit_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra ägare.
        /// </summary>
        public static string Edit_Owner {
            get {
                return ResourceManager.GetString("Edit_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra preset.
        /// </summary>
        public static string Edit_Preset {
            get {
                return ResourceManager.GetString("Edit_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra profil.
        /// </summary>
        public static string Edit_Profile {
            get {
                return ResourceManager.GetString("Edit_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra profilgrupp.
        /// </summary>
        public static string Edit_ProfileGroup {
            get {
                return ResourceManager.GetString("Edit_ProfileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra region.
        /// </summary>
        public static string Edit_Region {
            get {
                return ResourceManager.GetString("Edit_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra användare.
        /// </summary>
        public static string Edit_User {
            get {
                return ResourceManager.GetString("Edit_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ändra kodarmodell.
        /// </summary>
        public static string Edit_UserAgent {
            get {
                return ResourceManager.GetString("Edit_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutar med.
        /// </summary>
        public static string EndsWith {
            get {
                return ResourceManager.GetString("EndsWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det uppstod ett fel när kodaren skulle kontaktas.
        /// </summary>
        public static string ErrorGettingStatus {
            get {
                return ResourceManager.GetString("ErrorGettingStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anknytningsnummer.
        /// </summary>
        public static string ExtensionNumber {
            get {
                return ResourceManager.GetString("ExtensionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filternamn.
        /// </summary>
        public static string Filter_Name {
            get {
                return ResourceManager.GetString("Filter_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det finns redan ett filter med det angivna namnet.
        /// </summary>
        public static string Filter_Name_In_Use {
            get {
                return ResourceManager.GetString("Filter_Name_In_Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filtrera på.
        /// </summary>
        public static string Filter_On {
            get {
                return ResourceManager.GetString("Filter_On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filter.
        /// </summary>
        public static string Filters {
            get {
                return ResourceManager.GetString("Filters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förnamn.
        /// </summary>
        public static string First_Name {
            get {
                return ResourceManager.GetString("First_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Från.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generera lösenord.
        /// </summary>
        public static string Generate_Password {
            get {
                return ResourceManager.GetString("Generate_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genererat lösenord.
        /// </summary>
        public static string Generated_Password {
            get {
                return ResourceManager.GetString("Generated_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hämta.
        /// </summary>
        public static string Get {
            get {
                return ResourceManager.GetString("Get", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPO namnlista.
        /// </summary>
        public static string Gpo_Names {
            get {
                return ResourceManager.GetString("Gpo_Names", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ProfilGrupp.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupper.
        /// </summary>
        public static string Groups {
            get {
                return ResourceManager.GetString("Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lägg på.
        /// </summary>
        public static string Hangup {
            get {
                return ResourceManager.GetString("Hangup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag har bokat denna studio enligt gällande rutin.
        /// </summary>
        public static string HangUp_I_Have_Booked {
            get {
                return ResourceManager.GetString("HangUp_I_Have_Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag har kontrollerat att studion är tom och ingen verksamhet pågår.
        /// </summary>
        public static string HangUp_I_Have_Checked {
            get {
                return ResourceManager.GetString("HangUp_I_Have_Checked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koppla ner studio.
        /// </summary>
        public static string HangUp_Studio {
            get {
                return ResourceManager.GetString("HangUp_Studio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Höjd.
        /// </summary>
        public static string Height {
            get {
                return ResourceManager.GetString("Height", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hemsida.
        /// </summary>
        public static string Homepage {
            get {
                return ResourceManager.GetString("Homepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timme.
        /// </summary>
        public static string Hour {
            get {
                return ResourceManager.GetString("Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifierare.
        /// </summary>
        public static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange en identifierare.
        /// </summary>
        public static string Identifier_Required {
            get {
                return ResourceManager.GetString("Identifier_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifieringstyp.
        /// </summary>
        public static string IdentifyType {
            get {
                return ResourceManager.GetString("IdentifyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identitet.
        /// </summary>
        public static string Identity {
            get {
                return ResourceManager.GetString("Identity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bild.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importera.
        /// </summary>
        public static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I samtal med.
        /// </summary>
        public static string In_Call_With {
            get {
                return ResourceManager.GetString("In_Call_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingång nr.
        /// </summary>
        public static string Input_No {
            get {
                return ResourceManager.GetString("Input_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styrbara ingångar.
        /// </summary>
        public static string Inputs {
            get {
                return ResourceManager.GetString("Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Felaktigt användarnamn eller lösenord.
        /// </summary>
        public static string Invalid_Username_Password {
            get {
                return ResourceManager.GetString("Invalid_Username_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP-Adress.
        /// </summary>
        public static string Ip_Address {
            get {
                return ResourceManager.GetString("Ip_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Efternamn.
        /// </summary>
        public static string Last_Name {
            get {
                return ResourceManager.GetString("Last_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senast avslutade samtalen.
        /// </summary>
        public static string Latest_Closed_Calls {
            get {
                return ResourceManager.GetString("Latest_Closed_Calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linjestatus.
        /// </summary>
        public static string Line_Status {
            get {
                return ResourceManager.GetString("Line_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linjer.
        /// </summary>
        public static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringer.
        /// </summary>
        public static string LineStatus_Calling {
            get {
                return ResourceManager.GetString("LineStatus_Calling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppkopplad.
        /// </summary>
        public static string LineStatus_ConnectedCalled {
            get {
                return ResourceManager.GetString("LineStatus_ConnectedCalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectedDownloadingFile.
        /// </summary>
        public static string LineStatus_ConnectedDownloadingFile {
            get {
                return ResourceManager.GetString("LineStatus_ConnectedDownloadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppkopplad.
        /// </summary>
        public static string LineStatus_ConnectedReceived {
            get {
                return ResourceManager.GetString("LineStatus_ConnectedReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectedTestingLine.
        /// </summary>
        public static string LineStatus_ConnectedTestingLine {
            get {
                return ResourceManager.GetString("LineStatus_ConnectedTestingLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ConnectedUploadingFile.
        /// </summary>
        public static string LineStatus_ConnectedUploadingFile {
            get {
                return ResourceManager.GetString("LineStatus_ConnectedUploadingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frånkopplad.
        /// </summary>
        public static string LineStatus_Disconnected {
            get {
                return ResourceManager.GetString("LineStatus_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kopplar ner.
        /// </summary>
        public static string LineStatus_Disconnecting {
            get {
                return ResourceManager.GetString("LineStatus_Disconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initierar.
        /// </summary>
        public static string LineStatus_Initializing {
            get {
                return ResourceManager.GetString("LineStatus_Initializing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Förhandlar om DHCP.
        /// </summary>
        public static string LineStatus_NegotiatingDhcp {
            get {
                return ResourceManager.GetString("LineStatus_NegotiatingDhcp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NoPhysicalLine.
        /// </summary>
        public static string LineStatus_NoPhysicalLine {
            get {
                return ResourceManager.GetString("LineStatus_NoPhysicalLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ej tillgänglig.
        /// </summary>
        public static string LineStatus_NotAvailable {
            get {
                return ResourceManager.GetString("LineStatus_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tar emot samtal.
        /// </summary>
        public static string LineStatus_ReceivingCall {
            get {
                return ResourceManager.GetString("LineStatus_ReceivingCall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Åtekopplar.
        /// </summary>
        public static string LineStatus_Reconnecting {
            get {
                return ResourceManager.GetString("LineStatus_Reconnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ladda.
        /// </summary>
        public static string Load {
            get {
                return ResourceManager.GetString("Load", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laddad preset.
        /// </summary>
        public static string Loaded_Preset {
            get {
                return ResourceManager.GetString("Loaded_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plats.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platsgrupper.
        /// </summary>
        public static string Location_Groups {
            get {
                return ResourceManager.GetString("Location_Groups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Välj plats.
        /// </summary>
        public static string Location_Select {
            get {
                return ResourceManager.GetString("Location_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kortnamn.
        /// </summary>
        public static string Location_Short_Name {
            get {
                return ResourceManager.GetString("Location_Short_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Platser.
        /// </summary>
        public static string Locations {
            get {
                return ResourceManager.GetString("Locations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lås konto.
        /// </summary>
        public static string Lock_Account {
            get {
                return ResourceManager.GetString("Lock_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga in.
        /// </summary>
        public static string Log_In {
            get {
                return ResourceManager.GetString("Log_In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logga ut.
        /// </summary>
        public static string Log_Off {
            get {
                return ResourceManager.GetString("Log_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Längst.
        /// </summary>
        public static string Longest {
            get {
                return ResourceManager.GetString("Longest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string Max {
            get {
                return ResourceManager.GetString("Max", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metatypnamn.
        /// </summary>
        public static string MetaType_Name {
            get {
                return ResourceManager.GetString("MetaType_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Värde för metatyp.
        /// </summary>
        public static string MetaType_Value {
            get {
                return ResourceManager.GetString("MetaType_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metatyper.
        /// </summary>
        public static string MetaTypes {
            get {
                return ResourceManager.GetString("MetaTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string Min {
            get {
                return ResourceManager.GetString("Min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Namn.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ett namn.
        /// </summary>
        public static string Name_Required {
            get {
                return ResourceManager.GetString("Name_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nät IPv4.
        /// </summary>
        public static string Net {
            get {
                return ResourceManager.GetString("Net", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ett nät.
        /// </summary>
        public static string Net_Required {
            get {
                return ResourceManager.GetString("Net_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nät IPv6.
        /// </summary>
        public static string NetV6 {
            get {
                return ResourceManager.GetString("NetV6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt konto.
        /// </summary>
        public static string New_Account {
            get {
                return ResourceManager.GetString("New_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny stad.
        /// </summary>
        public static string New_City {
            get {
                return ResourceManager.GetString("New_City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny kodartyp.
        /// </summary>
        public static string New_Codec_Type {
            get {
                return ResourceManager.GetString("New_Codec_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nytt filter.
        /// </summary>
        public static string New_Filter {
            get {
                return ResourceManager.GetString("New_Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny grupp.
        /// </summary>
        public static string New_Group {
            get {
                return ResourceManager.GetString("New_Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny plats.
        /// </summary>
        public static string New_Location {
            get {
                return ResourceManager.GetString("New_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny metatyp.
        /// </summary>
        public static string New_MetaType {
            get {
                return ResourceManager.GetString("New_MetaType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny ägare.
        /// </summary>
        public static string New_Owner {
            get {
                return ResourceManager.GetString("New_Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny preset.
        /// </summary>
        public static string New_Preset {
            get {
                return ResourceManager.GetString("New_Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny profil.
        /// </summary>
        public static string New_Profile {
            get {
                return ResourceManager.GetString("New_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny profilgrupp.
        /// </summary>
        public static string New_ProfileGroup {
            get {
                return ResourceManager.GetString("New_ProfileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny region.
        /// </summary>
        public static string New_Region {
            get {
                return ResourceManager.GetString("New_Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny användare.
        /// </summary>
        public static string New_User {
            get {
                return ResourceManager.GetString("New_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ny kodarmodell.
        /// </summary>
        public static string New_UserAgent {
            get {
                return ResourceManager.GetString("New_UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen kodare kunde hittas.
        /// </summary>
        public static string No_Codec_Found {
            get {
                return ResourceManager.GetString("No_Codec_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen GPO kunde hittas.
        /// </summary>
        public static string No_Gpo_Found {
            get {
                return ResourceManager.GetString("No_Gpo_Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingen samtalshistorik.
        /// </summary>
        public static string No_Items_In_Filtered_Call_History {
            get {
                return ResourceManager.GetString("No_Items_In_Filtered_Call_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga pågående samtal.
        /// </summary>
        public static string No_Ongoing_Calls {
            get {
                return ResourceManager.GetString("No_Ongoing_Calls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inga registrerade enheter.
        /// </summary>
        public static string No_Registered_User_Agents {
            get {
                return ResourceManager.GetString("No_Registered_User_Agents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antal GPO:er.
        /// </summary>
        public static string NrOfGpos {
            get {
                return ResourceManager.GetString("NrOfGpos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Av.
        /// </summary>
        public static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to På.
        /// </summary>
        public static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pågående samtal.
        /// </summary>
        public static string OngoingCalls {
            get {
                return ResourceManager.GetString("OngoingCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa länk för alla.
        /// </summary>
        public static string Open_User_Interface {
            get {
                return ResourceManager.GetString("Open_User_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Markera kryssrutan för att visa länk till användargränssnitt för alla användare (och inte bara autenticerade användare).
        /// </summary>
        public static string Open_User_Interface_Description {
            get {
                return ResourceManager.GetString("Open_User_Interface_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Översikt.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ägare.
        /// </summary>
        public static string Owner {
            get {
                return ResourceManager.GetString("Owner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ägare.
        /// </summary>
        public static string Owners {
            get {
                return ResourceManager.GetString("Owners", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenorden matchar inte.
        /// </summary>
        public static string Password_Dont_Match {
            get {
                return ResourceManager.GetString("Password_Dont_Match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ett lösenord.
        /// </summary>
        public static string Password_Required {
            get {
                return ResourceManager.GetString("Password_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lösenordet är för kort.
        /// </summary>
        public static string Password_To_Short {
            get {
                return ResourceManager.GetString("Password_To_Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilgrupp.
        /// </summary>
        public static string ProfileGroup {
            get {
                return ResourceManager.GetString("ProfileGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange en profilgrupp.
        /// </summary>
        public static string ProfileGroup_Required {
            get {
                return ResourceManager.GetString("ProfileGroup_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profilgrupper.
        /// </summary>
        public static string ProfileGroups {
            get {
                return ResourceManager.GetString("ProfileGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiler.
        /// </summary>
        public static string Profiles {
            get {
                return ResourceManager.GetString("Profiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starta om.
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regioner.
        /// </summary>
        public static string Regions {
            get {
                return ResourceManager.GetString("Regions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registrerade enheter.
        /// </summary>
        public static string RegisteredSips {
            get {
                return ResourceManager.GetString("RegisteredSips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kom ihåg mig.
        /// </summary>
        public static string Remember_Me {
            get {
                return ResourceManager.GetString("Remember_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ta bort studio.
        /// </summary>
        public static string RemoveStudio {
            get {
                return ResourceManager.GetString("RemoveStudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill ta bort denna studio.
        /// </summary>
        public static string RemoveStudioAreYouSure {
            get {
                return ResourceManager.GetString("RemoveStudioAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kräver en ActiveX kompatibel webbläsare.
        /// </summary>
        public static string Requires_Activex {
            get {
                return ResourceManager.GetString("Requires_Activex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roll.
        /// </summary>
        public static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spara.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SDP.
        /// </summary>
        public static string SDP {
            get {
                return ResourceManager.GetString("SDP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sök konto.
        /// </summary>
        public static string Search_Account {
            get {
                return ResourceManager.GetString("Search_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skicka.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inställningar.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kortast.
        /// </summary>
        public static string Shortest {
            get {
                return ResourceManager.GetString("Shortest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa användartyp.
        /// </summary>
        public static string Show_User_Type {
            get {
                return ResourceManager.GetString("Show_User_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP.
        /// </summary>
        public static string SIP {
            get {
                return ResourceManager.GetString("SIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP-konton.
        /// </summary>
        public static string Sip_Accounts {
            get {
                return ResourceManager.GetString("Sip_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anslutningen till CCM är bruten.
        /// </summary>
        public static string Socket_Connection_Is_Lost_With_Server {
            get {
                return ResourceManager.GetString("Socket_Connection_Is_Lost_With_Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Återanslutningsförsök.
        /// </summary>
        public static string Socket_Connection_Reconnect_Attempts {
            get {
                return ResourceManager.GetString("Socket_Connection_Reconnect_Attempts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hastighetsmätning.
        /// </summary>
        public static string SpeedTest {
            get {
                return ResourceManager.GetString("SpeedTest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistik.
        /// </summary>
        public static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max under perioden.
        /// </summary>
        public static string Stats_MaxInPeriod {
            get {
                return ResourceManager.GetString("Stats_MaxInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Median för perioden.
        /// </summary>
        public static string Stats_MedianInPeriod {
            get {
                return ResourceManager.GetString("Stats_MedianInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtal (antal).
        /// </summary>
        public static string Stats_NumberOfCalls {
            get {
                return ResourceManager.GetString("Stats_NumberOfCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samtidiga samtal (maxantal).
        /// </summary>
        public static string Stats_NumberOfSimultaneousCalls {
            get {
                return ResourceManager.GetString("Stats_NumberOfSimultaneousCalls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} samtidiga samtal vid ett tillfälle:.
        /// </summary>
        public static string Stats_SimultaneousCallsToolTip1 {
            get {
                return ResourceManager.GetString("Stats_SimultaneousCallsToolTip1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} samtidiga samtal vid {1} tillfällen:.
        /// </summary>
        public static string Stats_SimultaneousCallsToolTipM {
            get {
                return ResourceManager.GetString("Stats_SimultaneousCallsToolTipM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tid på dygnet.
        /// </summary>
        public static string Stats_TimeOfDay {
            get {
                return ResourceManager.GetString("Stats_TimeOfDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total samtalstid (minuter).
        /// </summary>
        public static string Stats_TotalCallTimeInMinutes {
            get {
                return ResourceManager.GetString("Stats_TotalCallTimeInMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Steg.
        /// </summary>
        public static string Step {
            get {
                return ResourceManager.GetString("Step", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studior.
        /// </summary>
        public static string Studios {
            get {
                return ResourceManager.GetString("Studios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Till.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totalt.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slå Av/På.
        /// </summary>
        public static string Turn_On_Off {
            get {
                return ResourceManager.GetString("Turn_On_Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det gick inte att få kontakt med kodaren.
        /// </summary>
        public static string Unable_To_Connect_To_Codec {
            get {
                return ResourceManager.GetString("Unable_To_Connect_To_Codec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Det gick inte att matcha adressen till kodaren.
        /// </summary>
        public static string Unable_To_Resolve_Address {
            get {
                return ResourceManager.GetString("Unable_To_Resolve_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lås upp konto.
        /// </summary>
        public static string Unlock_Account {
            get {
                return ResourceManager.GetString("Unlock_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rullningslister.
        /// </summary>
        public static string Use_Scrollbars {
            get {
                return ResourceManager.GetString("Use_Scrollbars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användaren kunde inte sparas.
        /// </summary>
        public static string User_could_not_be_saved {
            get {
                return ResourceManager.GetString("User_could_not_be_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius användarimport.
        /// </summary>
        public static string User_Import_Radius {
            get {
                return ResourceManager.GetString("User_Import_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jag vill importera alla användare från RADIUS.
        /// </summary>
        public static string User_Import_Radius_Agree {
            get {
                return ResourceManager.GetString("User_Import_Radius_Agree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste godkänna importen.
        /// </summary>
        public static string User_Import_Radius_Agree_Needed {
            get {
                return ResourceManager.GetString("User_Import_Radius_Agree_Needed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Är du säker på att du vill köra importen?.
        /// </summary>
        public static string User_Import_Radius_Are_You_Sure {
            get {
                return ResourceManager.GetString("User_Import_Radius_Are_You_Sure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denna funktion importerar alla användare från RADIUS till CCM som inte redan finns i CCM. Importen är inte möjlig att återställa utan manuell hantering..
        /// </summary>
        public static string User_Import_Radius_Description {
            get {
                return ResourceManager.GetString("User_Import_Radius_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} användare har importerats..
        /// </summary>
        public static string User_Import_Radius_Imported {
            get {
                return ResourceManager.GetString("User_Import_Radius_Imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användargränssnitt.
        /// </summary>
        public static string User_Interface {
            get {
                return ResourceManager.GetString("User_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Använd [host] för att markera vart adress skall placeras. Ex https://[host]/adminui.
        /// </summary>
        public static string User_Interface_Description {
            get {
                return ResourceManager.GetString("User_Interface_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamnet är upptaget.
        /// </summary>
        public static string User_Name_Already_Taken {
            get {
                return ResourceManager.GetString("User_Name_Already_Taken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodarmodell.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodarmodeller.
        /// </summary>
        public static string UserAgents {
            get {
                return ResourceManager.GetString("UserAgents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användarnamn.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Du måste ange ett användarnamn.
        /// </summary>
        public static string UserName_Required {
            get {
                return ResourceManager.GetString("UserName_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Användare.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Webbgränssnitt.
        /// </summary>
        public static string Web_Interface {
            get {
                return ResourceManager.GetString("Web_Interface", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bred översikt.
        /// </summary>
        public static string Wide_Overview {
            get {
                return ResourceManager.GetString("Wide_Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bredd.
        /// </summary>
        public static string Width {
            get {
                return ResourceManager.GetString("Width", resourceCulture);
            }
        }
    }
}
