//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CCM.Core.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CCM.Core.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Börjar med.
        /// </summary>
        internal static string Begins_With {
            get {
                return ResourceManager.GetString("Begins_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Innehåller.
        /// </summary>
        internal static string Contains {
            get {
                return ResourceManager.GetString("Contains", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pool-kodare.
        /// </summary>
        internal static string Description_PoolCodec {
            get {
                return ResourceManager.GetString("Description_PoolCodec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanligt SIP-konto.
        /// </summary>
        internal static string Description_SipAccount {
            get {
                return ResourceManager.GetString("Description_SipAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIP-alias.
        /// </summary>
        internal static string Description_SipAlias {
            get {
                return ResourceManager.GetString("Description_SipAlias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slutar med.
        /// </summary>
        internal static string Ends_With {
            get {
                return ResourceManager.GetString("Ends_With", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Externt nummer.
        /// </summary>
        internal static string External_Phone_Number {
            get {
                return ResourceManager.GetString("External_Phone_Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ank.
        /// </summary>
        internal static string Internal_Phone_Connection_Prefix {
            get {
                return ResourceManager.GetString("Internal_Phone_Connection_Prefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reguljärt uttryck.
        /// </summary>
        internal static string Regular_Expression {
            get {
                return ResourceManager.GetString("Regular_Expression", resourceCulture);
            }
        }
    }
}
