version: "3.7"
services:
  ccm:
    image: ${IMAGE_NAME}
    environment:
      ASPNETCORE_URLS: http://+:80
    networks:
      - proxynet
      - default
    configs:
      - source: ccm_stage_appsettings
        target: /app/appsettings.json
    volumes:
      - /mnt/nfs/msc-nfs/docker-share/development/ccm:/ccm

configs:
  ccm_stage_appsettings:
    external: true

networks:
  proxynet:
    external: true

