def application = [
    stackname: "contrib",
    name: "ccm",
]

def jenkinsWorkerConstraint = "!arm"
def httpProxy = env.HTTP_PROXY
def dockerRegistry = env.DOCKER_REGISTRY
def dockerFile = "./ci/CCMWeb/Dockerfile"
def dockerImageEnvName = "IMAGE_NAME"
def dockerComposeFile = "./ci/CCMWeb/docker-compose.yml"

def config = [
    dockerHost: "msc.sr.se",
    dockerHostCredentialsId: "dockerHostUser",
    tempFilesPath: "/mnt/nfs/msc-nfs/stacks",
]

node(jenkinsWorkerConstraint) {
    stage("Clone repository") {
       checkout scm
    }

    def buildVersion = "0.0.0"
    def buildEnvironment = "Dev"
    def stageConfigFile = "ccm_stage_appsettings_2"

    // Use tag name as build version on production build (a build from a tag) - used in the bottom footer of main page in the application
    // Use specific configuration file on stage version (a build from a branch)
    if(env.TAG_NAME) {
        buildVersion = env.TAG_NAME
        buildEnvironment = "Prod"
        application.stackname = "ipk"
    }

    // Modify the buildinformation.json file in the repository
    sh "sed -i \"s/APP_VERSION/\"${buildVersion}\"/g\" ./CCM.Web/buildinformation.json"
    sh "sed -i \"s/APP_ENVIRONMENT/\"${buildEnvironment}\"/g\" ./CCM.Web/buildinformation.json"
    sh "sed -i \"s/APP_SERVER/\"${config.dockerHost}\"/g\" ./CCM.Web/buildinformation.json"

    sh '''
        BUILDINFORMATION="./CCM.Web/buildinformation.json"
        DATE=$(date '+%Y-%m-%d %H:%M:%S')
        sed -i "s/APP_NAME/Codec Control Monitor/g" $BUILDINFORMATION
        sed -i "s/APP_RELEASE_DATE/${DATE}/g" $BUILDINFORMATION
    '''
    // Print the modified file
    sh 'cat ./CCM.Web/buildinformation.json'

    def fullImageName
    docker.withRegistry(dockerRegistry) {
        stage("Build image") {
            def buildArgs = ["HTTP_PROXY=${httpProxy}", "HTTPS_PROXY=${httpProxy}", "http_proxy=${httpProxy}", "https_proxy=${httpProxy}"]
            def argsString = ""
            buildArgs.each{
                argsString += "--build-arg ${it} "
            }

            argsString += "-f ${dockerFile} ."

            image = docker.build("${application.stackname}-${application.name}", argsString)
        }

        stage("Push image to registry") {
            image.push()
        }

        fullImageName = image.imageName()
    }

    withCredentials([usernamePassword(credentialsId: config.dockerHostCredentialsId, passwordVariable: "pass", usernameVariable: "user")]) {
        def dockerHost = [
            allowAnyHosts: true,
            user: user,
            password: pass,
            host: config.dockerHost,
            name: config.dockerHost,
        ]

        def dockerComposeDest = "${config.tempFilesPath}/${env.BUILD_TAG}".replaceAll("\\s","-")

        stage("Update service on ${dockerHost.host}") {
            sshCommand remote: dockerHost, command: "mkdir -p ${dockerComposeDest}"
            sshPut remote: dockerHost, from: dockerComposeFile, into: "${dockerComposeDest}/docker-compose.yml"
            sshCommand remote: dockerHost, command: "${dockerImageEnvName}=${fullImageName} docker stack deploy -c ${dockerComposeDest}/docker-compose.yml ${application.stackname}"
        }
    }

    cleanWs notFailBuild: true
}
