version: "3.7"
services:
  discovery:
    image: ${IMAGE_NAME}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 20m
    deploy:
      placement:
          constraints: [node.role == manager]
    ports:
      - "82:80"
    configs:
      - source: discovery_appsettings
        target: /app/appsettings.json

configs:
  discovery_appsettings:
    external: true

