version: "3.7"
services:
  discovery:
    image: ${IMAGE_NAME}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 20m
    deploy:
      placement:
          constraints: [node.role == manager]
    networks:
      - proxynet
    extra_hosts:
      - "stage-ccm.sr.se:134.25.10.16"
    configs:
      - source: discovery_appsettings_stage
        target: /app/appsettings.json

networks:
  proxynet:
    name: proxynet
configs:
  discovery_appsettings_stage:
    external: true
