version: "3.9"
services:
  discovery:
    image: ${IMAGE_NAME}
    logging:
      driver: json-file
      options:
        max-file: "5"
        max-size: 20m
    deploy:
      placement:
          constraints: [node.role == manager]
    networks:
      - proxynet
    configs:
      - source: discovery_appsettings_stage
        target: /app/appsettings.json

networks:
  proxynet:
    external: true

configs:
  discovery_appsettings_stage:
    external: true
